### PR TITLE
Support tensorflow 2.16.1 and separate CI run for tensorflow estimator

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Resolve TODO in  `.github/workflows/tensorflow.yml`: 

```
        # NOTE(nabenabe0928): Got "AttributeError: module 'tensorflow' has no attribute 'estimator'".
        # TODO(nabenabe0928): Remove this version constraint.
        pip install "tensorflow<2.16.1"
```

The root error is that tensorflow 2.16.1 has broken backward compatibility for tensorflow estimator that is not available anymore. In my understanding, the alternative is keras, so we cannot use estimator examples with tensorflow 2.16.1 or higher.

## Description of the changes

- Revert the hotfix for TF introduced by https://github.com/optuna/optuna-examples/pull/245
- Add `RuntimeError` based on the tensorflow version for estimator example and add a new run in github CI for estimator scripts.
- Add python 3.12 because tensorflow 2.16.1 starts to support it. 

---

More background: TensorFlow estimator has been removed since TensorFlow 2.16.1 according to https://www.tensorflow.org/guide/estimator and https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1.

### CODE REVIEW

**Comment by nzw0301** [comment]
The failed runs will be fixed by #247.

**Comment by eukaryo** [comment]
I have re-run the CI checks.
@nabenabe0928 Could you review this PR?

**Review by nabenabe0928 — APPROVED** [review]
LGTM!
