### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'training_type_plugin'

### ISSUE THREAD

**Issue by EduardoCarvalho35** [optuna/optuna-examples#180]
## Note to the questioner

If you are more comfortable with [Stack Overflow], you may consider posting your question with the "optuna" tag there instead.
Alternatively, for issues that would benefit from more of an interactive session with the developers,
you may refer to the [optuna/optuna chat] on Gitter.

[Stack Overflow]: https://stackoverflow.com/questions/tagged/optuna
[optuna/optuna chat]: https://gitter.im/optuna/optuna

**Comment by nzw0301** [comment]
Could you share your optuna and pytorch-lightning versions?

**Comment by EduardoCarvalho35** [comment]
> Could you share your optuna and pytorch-lightning versions?

optuna version  : 3.1.0
pytorch_lightning version  : 2.0.0

**Comment by nzw0301** [comment]
Thanks 
Optuna doesn't support pytorch_lightning 2.0, as mentioned in https://github.com/optuna/optuna/issues/4524.

**Comment by Alnusjaponica** [comment]
Thank you for sharing the information. 
Actually, `PyTorchLightningPruningCallback` work with `pytorch_lightning==2.0` (See https://github.com/optuna/optuna-examples/pull/179) on master branch, but the test fails since the mock class depends on deprecated features. Therefore, you can use `pytorch_lightning==2.0` too if you used the master branch. Sorry for not updating the issue and make confusion.
